### ISSUE TITLE
Probable false positive on external semaphore validation

### ISSUE THREAD

**Issue by georgeouzou** [KhronosGroup/Vulkan-ValidationLayers#10211]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: NVIDIA GeForce RTX 5070 Ti, 576.40
 - SDK or header version if building from repo: 1.4.313.1
 - Options enabled (synchronization, best practices, etc.): Validation, Standard Preset (Vulkan Configurator)

**Issue**

I have the following case:
- the first submit finishes and signals an external timeline semaphore for a external API denoiser
- the denoiser waits for the external timeline semaphore and signals it when completing its work
- then another submit is waiting at the above external timeline semaphore as well as a binary semaphore for the acquisition of the swapchain image, does some post-processing work and signals a "render-finished" binary semaphore
- the final present submit is waiting at the "render-finished" binary semaphore and presents the swapchain image

The following validation error is reported, which i think is a false positive:

> vkQueuePresentKHR(): pPresentInfo->pWaitSemaphores[0] queue (VkQueue 0x218d2150a60) is waiting on binary semaphore (VkSemaphore 0x80000000008) that has an associated signal but it depends on timeline semaphore wait (VkSemaphore 0x20000000002, wait value = 2) that does not have resolving signal submitted yet.
> The Vulkan spec states: All elements of the pWaitSemaphores member of pPresentInfo must reference a semaphore signal operation that has been submitted for execution and any semaphore signal operations on which it depends must have also been submitted for execution (https://vulkan.lunarg.com/doc/view/1.4.313.1/windows/antora/spec/latest/chapters/VK_KHR_surface/wsi.html#VUID-vkQueuePresentKHR-pWaitSemaphores-03268)

**Comment by artem-lunarg** [comment]
@georgeouzou We fixed one issue with external timeline semaphore tracking recently (after 1.4.313.1 SDK release): https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10100.  Do you have an opportunity to check if it fixes the issue? You can either build the latest code or use pre-build dll (https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/15499796566/artifacts/3279333480)

**Comment by georgeouzou** [comment]
@artem-lunarg i used the pre-build dll within the vulkan configurator but the issue still persists

**Comment by artem-lunarg** [comment]
@georgeouzou thanks for checking! Just to be sure dll was actually loaded, did you replace existing dll? or did you put json file (with the same name as dll, as we have in sdk) next to provided dll?

**Comment by georgeouzou** [comment]
@artem-lunarg i copied the json file to the provided dll. Do i need to change something in the json itself?

**Comment by artem-lunarg** [comment]
No, it should be fine if json is copied. VkConfig also shows the name of json that is currently in use (screenshot below). I usually use some tool to be sure dll is loaded. In Visual Studio, the output windows shows loaded dll, or Microsoft's standalone Process Explorer tool. Anyway, I will try to write a test that reproduces this issue.

![Image](https://github.com/user-attachments/assets/6ba2060d-843c-425e-96b3-a6b009ba0652)

**Comment by georgeouzou** [comment]
@artem-lunarg i can provide the sample to reproduce this.

**Comment by artem-lunarg** [comment]
@georgeouzou yes please, would be very helpful. If needed we have internal sharing service to upload files, or if it’s public repo the link will work.

**Comment by georgeouzou** [comment]
@artem-lunarg, I prepared a [branch ](https://github.com/georgeouzou/vk_exp/tree/external_semaphore_validation) with a dummy cuda denoiser that reproduces the issue.

**Comment by artem-lunarg** [comment]
Hm.. I tried both ways to open folder in vs and also tried to build as "cmake -S . -B build", in both cases I could build, but when tried to run it can't find path to obj file. 

update: I udpated path to "Debug/resources/bmw.obj" in the source code, now LoadObj can load the model, but load_model() fails later when tries to set materials, and the data is corrupted there. Do I need some material file?

**Comment by georgeouzou** [comment]
No, it should work as is by following the steps:
- git clone https://github.com/georgeouzou/vk_exp.git
- cd vk_exp
- git submodule update --init --recursive
- git checkout external_semaphore_validation
- open folder in visual studio
- build & run

The executable needs to find the "resources/bmw.obj" and "resources/bmw.mtl" file but the download and the copy of these files should be done automatically through cmake.

**Comment by artem-lunarg** [comment]
Thanks, I forgot to checkout the branch. It works now and I can reproduce the issue.

**Comment by artem-lunarg** [comment]
@georgeouzou it works now with the sample app
