### ISSUE TITLE
Validation layer crashes in ValidationStateTracker::AddCommandBufferBindingImage when calling vkCmdCopyImage and dstImage is a swapchain image

### ISSUE THREAD

**Issue by Valakor** [KhronosGroup/Vulkan-ValidationLayers#1312]
The parameter `IMAGE_STATE *image_state` is nullptr - is there no recorded image state for swap chain images? I assume this will affect any of the functions in `state_tracker.cpp` that accept an image that might have been obtained from a swap chain.

Some extra details:

- SDK version 1.1.121
- Occurs on both MacOS (MoltenVK) and Windows
- Only occurs when enabling `VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT`

**Comment by mark-lunarg** [comment]
There was an issue with best practices in 1.1.121 which was addressed in a point release, 1.1.121.1.  Can you please confirm you are using SDK 1.1.121.1 or later?

**Comment by jeffbolznv** [comment]
It looks like core and statetracker still have this bug, e.g. see ValidationStateTracker::PreCallRecordCmdCopyImage
