### ISSUE TITLE
vk_khr_display fails with FindObject assertion

### ISSUE THREAD

**Issue by lukexi** [KhronosGroup/Vulkan-ValidationLayers#1987]
I seem to be having a similar issue to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1569 (which was marked as fixed in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1573) — I'm trying to render direct to display on Arch/AMD using validation layers 1.2.141.0 and receiving
```
main.app: /build/vulkan-validation-layers/src/Vulkan-ValidationLayers-sdk-1.2.141.0/layers/generated/thread_safety.h:144: std::shared_ptr<ObjectUseData> counter<T>::FindObject(T) [with T = VkDisplayKHR_T*]: Assertion `object_table.contains(object)' failed.
```
when calling `vkGetDisplayPlaneSupportedDisplaysKHR`

**Comment by lukexi** [comment]
If I bypass the call to `vkGetDisplayPlaneSupportedDisplaysKHR`, my code then fails with the same assertion on `vkGetDisplayPlaneCapabilitiesKHR`. If I bypass that too, I can successfully make it to `vkCreateDisplayPlaneSurfaceKHR` and everything works great.

**Comment by mark-lunarg** [comment]
@lukexi, I have pushed a branch, `markl-threadobjects-1987` with a potential fix -- are you able to build the layers from the repo to give it a quick test?

**Comment by lukexi** [comment]
Hi Mark, thanks so much! I tested just now, and it is now able to get past `vkGetDisplayPlaneSupportedDisplaysKHR` but still fails on `vkGetDisplayPlaneCapabilitiesKHR`

```
About to call vkGetDisplayPlaneCapabilitiesKHR...
main.app: /home/dynamic/Code/Vulkan-ValidationLayers/layers/generated/thread_safety.h:144: std::shared_ptr<ObjectUseData> counter<T>::FindObject(T) [with T = VkDisplayModeKHR_T*]: Assertion `object_table.contains(object)' failed.
```

**Comment by mark-lunarg** [comment]
@lukexi , yeah, this is a mess.  Did an audit this morning and nearly all of the VkDisplayKHR and VkDisplayModeKHR handling is borked in this layer.  I believe there are also holes in ObjectTracker as mentioned in issue #1660.  I will do a cleanup pass on both to try to get this all working at once.  Insert sarcastic comment here about how the Vulkan API creates objects using non-standard conventions!
