### ISSUE TITLE
Wrong Validation Message when destroying ressource in descriptor set with partially bound flag

### ISSUE THREAD

**Issue by Ipotrick** [KhronosGroup/Vulkan-ValidationLayers#3729]
**Describe the Issue**
When using a descriptor set, created with the partially bound bit and destroying a ressource in that set wich is not 'dynamicly used' by a shader the validation layers give a false positive error message like below.
When turning on gpu assisted validation this false positive message dissapears indicating there is indeed a bug in the validation layers.

**Valid Usage ID**
creating a descriptor set with the VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT,
binding an image
using the set in a shader (but not the image, the image is in a descriptor array and is not used in the shader)
destroying the image that is not used.
cause this false validation message:
> VUID-vkDestroyBuffer-buffer-00922(ERROR / SPEC): msgNum: -464217071 - Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] Object 0: handle = 0x4868e6000000005a, name = primitiveInfoBuffer, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xe4549c11 | Cannot free VkBuffer 0x4868e6000000005a[primitiveInfoBuffer] that is in use by a command buffer. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)
>     Objects: 1
>         [0] 0x4868e6000000005a, type: 9, name: primitiveInfoBuffer
> [ERROR: Validation]
> Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] Object 0: handle = 0x4868e6000000005a, name = primitiveInfoBuffer, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xe4549c11 | Cannot free VkBuffer 0x4868e6000000005a[primitiveInfoBuffer] that is in use by a command buffer. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)

**Environment:**
 - OS: Windows 10 
 - GPU: GTX 1080ti Driver: 511.23
 - SDK or header version if building from repo: 1.2.198.1, layers build from master: 58caea82d2cb199142f93664475fc413f03bd26e
 - Options enabled (synchronization, best practices, etc.):
 Core, Handle Wrapping, Object Lifetime, Stateless Parameter

**Additional context**
The set that is refered to above is very big four descriptor arrays with each 1024 descriptors. 
I am also using dynamic rendering wich is not fully supported yet.

**Comment by ncesario-lunarg** [comment]
Thank you for the issue @Ipotrick. My understanding of `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT` was that it allowed a bound descriptor set to contain invalid _descriptors_ ("invalid" in the sense the descriptor had never been updated, or perhaps had mis-matching view and image types, etc.). However, I'm not seeing anything in the spec to indicate it is legal to destroy a _buffer_ while it is referenced in a command buffer that has not finished execution; VUID 00922 seems pretty clear. Is there an exception to 00922?

**Comment by Ipotrick** [comment]
Thank you for the response! I am still new vulkan and have trouble navigating the spec (i didnt know what VUID's or "valid usages id's" were until now haha). I see that the description of vkDestroyBuffer souhld have a list of all valid usages and as mine is not listed it appears that you are right and i missinterpreted the flag.
For completeness, i also use the flag VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT.
The way i am doing it now (wich doesnt yield any errors):
0. use the null descriptor feature.
1. write descriptor set with null descriptor at the place where the buffer descriptor is.
2. destroy buffer.

With my new understanding there would still be a bug in the validation tho. When enabling the gpu-assisted validation the validation error goes away! I tried all combinations in the gpu asssisted validation sub settings, all seem to result in that the error dissapears.

**Comment by plasmacel** [comment]
> ("invalid" in the sense the descriptor had never been updated, or perhaps had mis-matching view and image types, etc.).

This is pure assumption, the specification doesn't narrow what is considered an invalid descriptor here.

> VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT indicates that descriptors in this binding that are not dynamically used need not contain valid descriptors at the time the descriptors are consumed. A descriptor is dynamically used if any shader invocation executes an instruction that performs any memory access using the descriptor.

> VUID-vkDestroyBuffer-buffer-00922
All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution

I don't think this VUID extend to a buffer which is used in an **unused** descriptor of a descriptor set, for multiple reasons:
- the descriptor set is not a command, nor a VkBufferView
- VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT allows the descriptor to be non-valid if it is not dynamically used

**Comment by ncesario-lunarg** [comment]
@Ipotrick no worries, I think #3719 should resolve this (at least to some extent; we can't know which descriptors are used/unused without further GPU instrumentation), but it might be worth grabbing that change and try it out if you are able to build the validation layers. The spec isn't very clear here IMHO.

As to why the validation error goes away when GPU-AV is used, this is likely due to the fact that GPU-AV inserts `vkQueueWaitIdle`s between draws (@Tony-LunarG can correct me if this is wrong), so in the GPU-AV case, the command buffer--which was _in flight_ when `vkDestroyBuffer` was called in the non-GPU-AV case--is guaranteed to have finished before the call to `vkDestroyBuffer` (assuming a single threaded).

**Comment by Tony-LunarG** [comment]
Actually, when GPU-AV calls vkQueueWaitIdle, it calls directly into the driver, not through any validation layers that would clean up any command buffer state, so I don't think GPU-AV's vkQueueWaitIdle explains the error going away.  It is recommended that you turn off core validation when using GPU-AV, is it possible that is what happened?

**Comment by Zino2201** [comment]
Hello! I also just had this exact problem in the same conditions with the latest Vulkan SDK, also tried building HEAD but it isn't fixed.

**Comment by Ipotrick** [comment]
Yes. Sorry for the delayed response. xD
