### ISSUE TITLE
Validation of stencil ops complaining about read-only layout while writemask is 0

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#4921]
Since 0e4dc22c2, ANGLE is hitting a validation error (VUID `VUID-vkCmdDraw-None-06887`) in this condition:

- Pipeline's stencil ops are not KEEP
- Stencil test is enabled
- Stencil write mask is 0 (dynamic state)

The complaint is:

> The layout (VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL) of the stencil aspect of the depth/stencil attachment in the render pass is read only but not all stencil ops are VK_STENCIL_OP_KEEP.
front = { .failOp = VK_STENCIL_OP_REPLACE,  .passOp = VK_STENCIL_OP_REPLACE , .depthFailOp = VK_STENCIL_OP_REPLACE }
back = { .failOp = VK_STENCIL_OP_REPLACE, .passOp = VK_STENCIL_OP_REPLACE, .depthFailOp = VK_STENCIL_OP_REPLACE }
 The Vulkan spec states: If the current render pass instance uses a depth/stencil attachment with a read-only layout for the stencil aspect and stencil test is enabled, all stencil ops must be VK_STENCIL_OP_KEEP

However, ANGLE's behavior is logically correct; all write is masked off, so it shouldn't matter what the ops are. @spencer-lunarg should the VU be fixed?

**Comment by spencer-lunarg** [comment]
related issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4137 - this VUIDs were added in response to your internal issue https://gitlab.khronos.org/vulkan/vulkan/-/issues/3110  (for future tracking references)

I think the issue, in your case at least, is that `VK_DYNAMIC_STATE_STENCIL_WRITE_MASK` is not being taken into account... agree that this seems like the VUID needs a spec update, but can get a pending Validation Layer changes going orthogonally too

**Comment by spencer-lunarg** [comment]
The 1.3.237 spec fixed the language, just need to get a test done and can get a fix pushed up soon

**Comment by ShabbyX** [comment]
So I noticed this lying around and tried to remove the VU suppressions in https://chromium-review.googlesource.com/c/angle/angle/+/4103721, and I still see failures coming in.

Basically, ANGLE doesn't care about e.g. stencil ops when stencil write mask is 0 (because whatever the ops are, the result is the same). Did we reach a conclusion at some point whether that's correct or not? Does spec require all dynamic state to be set correctly regardless of whether they are effective?

**Comment by spencer-lunarg** [comment]
The check is guarded with

```c++
 const bool write_mask_enabled = (front.writeMask != 0) && (back.writeMask != 0);

 if (!all_keep_op && write_mask_enabled) {
 ```
 
 and these are gathered from `VK_DYNAMIC_STATE_STENCIL_WRITE_MASK` so curious what is still wrong, you have a test I can run to try and reproduce

**Comment by ShabbyX** [comment]
Yes sure, try `./angle_end2end_tests --gtest_filter=FramebufferTest_ES31.DepthStencilResolveThenChangeAttachmentThenResolveAgain/ES3_1_Vulkan` (after unsuppressing the VU failure, you can take https://chromium-review.googlesource.com/c/angle/angle/+/4103721).

The first failure is:

> [ VUID-vkCmdDraw-None-06887 ] Object 0: handle = Graphics Pipeline 312, type = VK_OBJECT_TYPE_PIPELINE; Object 1: handle = Render Pass 324, type = VK_OBJECT_TYPE_RENDER_PASS; Object 2: handle = Command Buffer 168, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x1044e121 | vkCmdDraw():  The layout (VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL) of the stencil aspect of the depth/stencil attachment in the render pass is read only but not all stencil ops are VK_STENCIL_OP_KEEP.
front = { .failOp = VK_STENCIL_OP_REPLACE,  .passOp = VK_STENCIL_OP_REPLACE , .depthFailOp = VK_STENCIL_OP_REPLACE }
back = { .failOp = VK_STENCIL_OP_REPLACE, .passOp = VK_STENCIL_OP_REPLACE, .depthFailOp = VK_STENCIL_OP_REPLACE }
The Vulkan spec states: If the current render pass instance uses a depth/stencil attachment with a read-only layout for the stencil aspect, both front and back writeMask are not zero, and stencil test is enabled, all stencil ops must be VK_STENCIL_OP_KEEP (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-None-06887)

And it's on a draw call that has this dynamic state:

![image](https://github.com/user-attachments/assets/a5905e03-b3c5-43d4-a99e-bcdfbadba501)

Rasterizer discard is _not_ enabled ;)

**Comment by ShabbyX** [comment]
Ok I guess VVL is checking for write mask 0, but not whether stencil testing is enabled at all?

**Comment by spencer-lunarg** [comment]
reopening issue, currently in "get SDK out the door mode" and will have L1 mental cache space for Dynamic State soon

**Comment by spencer-lunarg** [comment]
@ShabbyX (going through backlog today)

I tried `--gtest_filter=FramebufferTest_ES31.DepthStencilResolveThenChangeAttachmentThenResolveAgain/ES3_1_Vulkan` with VUID removed in vk_renderer.cpp and not seeing the VU on my RADV machine

Can you confirm you are still seeing this and on which machines (I have redone a lot of things around these dynamic states in the last year)

**Comment by ShabbyX** [comment]
@spencer-lunarg Finally got around to this, it still reproduces: https://chromium-review.googlesource.com/c/angle/angle/+/6809115

I ran only the Linux bots (Nvidia and Intel), they both reproduce this: https://ci.chromium.org/ui/p/angle/builders/try/linux-test/29506/overview (let me know if you can't see this page).

**Comment by spencer-lunarg** [comment]
.... @ShabbyX sorry to ask, but I tried this test again on my Intel machine and see not false positive and also stepping in it with a debugger, I see it does not get through all these conditions

```c++
 if (attachment_info.IsStencil() && last_bound_state.IsStencilTestEnable()) {
            VkStencilOpState front = last_bound_state.GetStencilOpStateFront();
            VkStencilOpState back = last_bound_state.GetStencilOpStateBack();

            const bool all_keep_op = ((front.failOp == VK_STENCIL_OP_KEEP) && (front.passOp == VK_STENCIL_OP_KEEP) &&
                                      (front.depthFailOp == VK_STENCIL_OP_KEEP) && (back.failOp == VK_STENCIL_OP_KEEP) &&
                                      (back.passOp == VK_STENCIL_OP_KEEP) && (back.depthFailOp == VK_STENCIL_OP_KEEP));
            const bool write_mask_enabled = (front.writeMask != 0) && (back.writeMask != 0);

            if (!all_keep_op && write_mask_enabled) {
```

Since I have dynamic state and all of this stuff in my mental L1 cache ... Could you re-try the gerrit commit, send me a link here, and I will watch out for the failure and look more into it from there

**Comment by ShabbyX** [comment]
Sure, I rebased and kicked off a new bot run in https://chromium-review.googlesource.com/c/angle/angle/+/6809115

**Comment by ShabbyX** [comment]
Unsuppression landed!
